[package]
name = "upnp"
version = "0.1.0"
authors = ["Jakob Hellermann <jakob.hellermann@protonmail.com>"]
edition = "2018"

[dependencies]
ssdp = "0.7.0"
serde = { version = "1.0.91", features = ["derive"] }
serde-xml-rs = "0.3.1"
xmltree = "0.8.0"
futures-preview = { version = "0.3.0-alpha.16", features = ["io-compat"] }
futures01 = { package = "futures", version = "0.1" }
hyper = "0.12.29"
getset = "0.0.7"
failure = "0.1.5"

[dev-dependencies]
runtime = "0.3.0-alpha.4"
runtime-tokio = "0.3.0-alpha.4"
