[package]
name = "upnp"
version = "0.1.0"
authors = ["Jakob Hellermann <jakob.hellermann@protonmail.com>"]
readme = "README.md"
repository = "https://github.com/jjakobh/upnp"
description = "An asynchronous library for finding UPnP control points, performing actions on them and reading their service descriptions."
categories = ["network-programming", "asynchronous"]
keywords = ["async", "upnp", "networking", "protocols"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
async-std = "1.0"
futures-util = "0.3"
get_if_addrs = "0.5"
genawaiter = { version = "0.2", features = ["futures03"] }
http = "0.1"
ssdp-client = "0.5"
roxmltree = "0.7"
isahc = { version = "0.8", default-features = false, features = ["http2"] }

[dev-dependencies]
futures = "0.3"
pin-utils = "0.1.0-alpha"
