[package]
name = "upnp"
version = "0.1.0"
authors = ["Jakob Hellermann <jakob.hellermann@protonmail.com>"]
edition = "2018"

[dependencies]
futures-preview = "0.3.0-alpha.17"
hyper = { git = "https://github.com/hyperium/hyper" }

serde = { version = "1.0", features = ["derive"] }
ssdp = { path = "../ssdp" }
serde-xml-rs = "0.3"
xmltree = "0.8"

getset = "0.0.7"
failure = "0.1"
log = "0.4.7"

[dev-dependencies]
tokio = { git = "https://github.com/tokio-rs/tokio" }
