[package]
name = "rupnp"
version = "0.1.0"
authors = ["Jakob Hellermann <jakob.hellermann@protonmail.com>"]
readme = "README.md"
repository = "https://github.com/jjakobh/upnp"
description = "An asynchronous library for finding UPnP control points, performing actions on them and reading their service descriptions."
categories = ["network-programming", "asynchronous"]
keywords = ["async", "upnp", "networking", "protocols"]
license = "MIT/Apache-2.0"
edition = "2018"

[features]
full_device_spec = []

[dependencies]
async-std = "1"
futures-util = { version = "0.3", default-features = false }
get_if_addrs = "0.5"
genawaiter = { version = "0.99", features = ["futures03"] }
http = "0.2"
ssdp-client = "0.5"
roxmltree = "0.9"
isahc = "0.9"

[dev-dependencies]
async-std = { version = "1.0", features = ["attributes"] }
futures = "0.3"
pin-utils = "0.1.0-alpha"
