[package]
name = "upnp"
version = "0.1.0"
authors = ["Jakob Hellermann <jakob.hellermann@protonmail.com>"]
edition = "2018"

[dependencies]
futures-preview = "0.3.0-alpha.18"
surf = "1.0.2"
serde = { version = "1.0.101", features = ["derive"] }
serde-xml-rs = "0.3.1"
ssdp-client = { path = "../ssdp-client" }
roxmltree = "0.7.1"
err-derive = "0.1.6"

[dev-dependencies]
futures-async-stream = "0.1.0-alpha.7"
async-std = "0.99.8"
