[package]
name = "upnp"
version = "0.1.0"
authors = ["Jakob Hellermann <jakob.hellermann@protonmail.com>"]
edition = "2018"

[dependencies]
futures-preview = "0.3.0-alpha.17"
hyper = { git = "https://github.com/hyperium/hyper" }

serde = { version = "1.0.94", features = ["derive"] }
ssdp = { path = "../ssdp" }
serde-xml-rs = "0.3.1"
xmltree = "0.8.0"

getset = "0.0.7"
failure = "0.1.5"

[dev-dependencies]
runtime = "0.3.0-alpha.6"
runtime-tokio = "0.3.0-alpha.5"
