[package]
name = "upnp"
version = "0.1.0"
authors = ["Jakob Hellermann <jakob.hellermann@protonmail.com>"]
readme = "README.md"
repository = "https://github.com/jjakobh/upnp"
description = "An asynchronous library for finding UPnP control points, performing actions on them and reading their service descriptions."
categories = ["network-programming", "asynchronous"]
keywords = ["async", "upnp", "networking", "protocols"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
async-std = { version = "0.99.11", features = ["unstable"] }
futures-async-stream = "0.1.0-alpha.7"
futures-util-preview = "0.3.0-alpha.19"
get_if_addrs = "0.5.3"
http = "0.1.19"
isahc = { version = "0.7.4", default-features = false, features = ["http2"] }
ssdp-client = { path = "../ssdp-client" }
roxmltree = "0.7.1"
