[package]
name = "upnp"
version = "0.1.0"
authors = ["Jakob Hellermann <jakob.hellermann@protonmail.com>"]
readme = "README.md"
repository = "https://github.com/jjakobh/upnp"
description = "An asynchronous library for finding UPnP control points, performing actions on them and reading their service descriptions."
categories = ["network-programming", "asynchronous"]
keywords = ["async", "upnp", "networking", "protocols"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
futures-util-preview = "0.3.0-alpha.19"
isahc = { version = "0.7.4", default-features = false, features = ["http2"] }
ssdp-client = { path = "../ssdp-client" }
roxmltree = "0.7.1"

[dev-dependencies]
async-std = "0.99.11"
pin-utils = "0.1.0-alpha.4"
